config/routes.rb
Spree::Core::Engine.routes.draw do
  patch '/save_quote_cart', to: 'orders#save_as_quote_cart', as: :save_as_quote_cart

  namespace :admin do
    resources :quotes, except: [:show] do
      member do
        get :cart
        get "/adjustments/unfinalize", to: "quotes#unfinalize_adjustments"
        get "/adjustments/finalize", to: "quotes#finalize_adjustments"
        post :send_to_user
        post :save_as_order
        get :quote_request
      end

      resources :adjustments, controller: "quotes/adjustments"
      resource :customer, controller: "quotes/customer_details"

      collection do
        resources 'quote_requests', controller: 'quotes/requests', only: [:index, :show] do
          member do
            get 'create_quote', to: 'quotes/requests#create_quote'
          end
        end
      end
    end
  end

  resources :quotes do
    member do
      get :approve
      get :place_into_cart
      get :leave_it
    end
  end

  resources :quote_requests, only: [:new, :create, :show] do
    post :comment, to: 'quote_requests#create_comment', on: :collection
  end
end

app/models/spree/quote.rb
module Spree
  class Quote < Order
    # Callbacks
    after_initialize :set_initial_config

    # Associations
    has_one :quote_details, class_name: Spree::QuoteDetails, foreign_key: 'spree_order_id', dependent: :destroy
    has_one :quote_request, class_name: Spree::QuoteRequest, foreign_key: 'spree_order_id', dependent: :nullify

    delegate :processing_quote?, :approved_by_user?,
      :needs_revision?, :requested?, :confirmation_delivered?, to: :quote_details, prefix: true

    # Scopes
    default_scope { as_quote }
    scope :as_quote, ->() { where(is_quote: true) }

    # Overriding methods
    def self.model_name
      ActiveModel::Name.new(self, nil, "Quote")
    end

    def quote_details
      super || (self.id?? Spree::QuoteDetails.find_or_create_by(spree_order_id: self.id) : nil)
    end

    # Redefining checkout_flow by adding quote step
    # checkout_flow do
    #   go_to_state :quote, if: ->(quote) { quote.quote_state == "ready" || quote.is_quote? || quote.quote_closed? }
    #   go_to_state :address
    #   go_to_state :delivery
    #   go_to_state :payment, if: ->(order) { order.payment_required? }
    #   go_to_state :confirm
    # end
    #
    # state_machine.before_transition from: :quote, do: :ensure_line_items_present

    def send_quote_to_user
      updater.update_quote_state
      updater.update
      deliver_quote_email
    end

    def finish_quote
      update_column(:quote_closed, true)
      updater.update_quote_state
      updater.update
      deliver_quote_finished_email
    end

    def send_quote_request_notification
      deliver_quote_request_notification
    end

    def approve!
      touch :quote_approved_at
      quote_details.update_column(:approved, true)
      updater.update_quote_state
      updater.update
    end

    def deliver_quote_email
      Spree::QuoteMailer.quote_email(self).deliver_later
      quote_details.update_column(:confirmation_delivered, true)
    end

    def deliver_quote_finished_email
      Spree::QuoteMailer.finish_quote_email(self).deliver_later
      update_column(:quote_closed, true)
    end

    def deliver_quote_request_notification
      Spree::QuoteMailer.quote_request_notification_email(self.quote_request).deliver_later
      Spree::QuoteMailer.admin_quote_request_notification_email(self.quote_request).deliver_later
      quote_details.update_column(:request_notification_delivered, true)
    end

    private
    def set_initial_config
      self.quote_details = Spree::QuoteDetails.find_or_initialize_by(spree_order_id: self.id)
    end
  end
end

app/controllers/spree/admin/quotes/adjustments_controller.rb
module Spree
  module Admin
    module Quotes
      class AdjustmentsController < ResourceController
        belongs_to 'spree/quote', find_by: :number

        create.after :update_totals
        destroy.after :update_totals
        update.after :update_totals

        skip_before_action :load_resource, only: [:toggle_state, :edit, :update, :destroy]

        before_action :find_adjustment, only: [:destroy, :edit, :update]

        helper_method :reasons_for

        def index
          @adjustments = @quote.all_adjustments.order("created_at ASC")
        end

        private

        def find_adjustment
          # Need to assign to @object here to keep ResourceController happy
          @adjustment = @object = parent.all_adjustments.find(params[:id])
        end

        def update_totals
          @quote.reload.update!
        end

        # Override method used to create a new instance to correctly
        # associate adjustment with quote
        def build_resource
          parent.adjustments.build(order: parent)
        end

        def reasons_for(_adjustment)
          [
            Spree::AdjustmentReason.active.to_a,
            @adjustment.adjustment_reason
          ].flatten.compact.uniq.sort_by { |r| r.name.downcase }
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes/customer_details_controller.rb
module Spree
  if defined? Backend
    module Admin
      module Quotes
        class CustomerDetailsController < Spree::Admin::BaseController
          rescue_from Spree::Quote::InsufficientStock, with: :insufficient_stock_error

          before_action :load_quote

          def show
            edit
          end

          def edit
            country_id = Spree::Country.default.id
            @quote.build_bill_address(country_id: country_id) if @quote.bill_address.nil?
            @quote.build_ship_address(country_id: country_id) if @quote.ship_address.nil?

            @quote.bill_address.country_id = country_id if @quote.bill_address.country.nil?
            @quote.ship_address.country_id = country_id if @quote.ship_address.country.nil?
          end

          def update
            if @quote.contents.update_cart(quote_params)

              if should_associate_user?
                requested_user = Spree.user_class.find(params[:user_id])
                @quote.associate_user!(requested_user, @quote.email.blank?)
              end

              unless @quote.quote_request
                create_quote_request
                @quote.send_quote_request_notification
              end

              unless @quote.completed?
                @quote.next
                @quote.refresh_shipment_rates
              end

              flash[:success] = Spree.t('customer_details_updated')
              redirect_to cart_admin_quote_url(@quote)
            else
              render action: :edit
            end
          end

          private

          def quote_params
            params.require(:order).permit(
              :email,
              :use_billing,
              :company,
              :sales_rep_id,
              :doc_hours_from,
              :doc_hours_to,
              bill_address_attributes: permitted_address_attributes,
              ship_address_attributes: permitted_address_attributes,
            )
          end

          def load_quote
            @quote = Spree::Quote.includes(:adjustments).find_by_number!(params[:quote_id])
          end

          def model_class
            Spree::Quote
          end

          def should_associate_user?
            params[:guest_checkout] == "false" && params[:user_id] && params[:user_id].to_i != @quote.user_id
          end

          def insufficient_stock_error
            flash[:error] = Spree.t(:insufficient_stock_for_order)
            redirect_to edit_admin_quote_customer_url(@quote)
          end

          def create_quote_request
            @qr ||= @quote.create_quote_request(
              user_id: @quote.user_id,
              status: Spree::QuoteRequest.statuses[:approved]
            )
            @qr.guest_email = @quote.email if @qr.user_id.blank?
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes/requests_controller.rb
module Spree
  if defined? Backend
    module Admin
      module Quotes
        class RequestsController < Spree::Admin::BaseController
          before_action :load_quote_request, only: [:show, :create_quote]

          def index
            query_present = params[:q]

            @search = Spree::QuoteRequest.accessible_by(current_ability, :index).ransack(params[:q])
            @quote_requests = if query_present
              @search.result(distinct: true)
            else
              @search.result
            end

            @quote_requests = @quote_requests.page(params[:page]).
              per(params[:per_page] || Spree::Config[:orders_per_page])
          end

          def show
            @comment = Spree::QuoteComment.new(by_admin: true, commentable: @quote_request)
          end

          def create_quote
            user = Spree.user_class.find_by_id(params[:user_id]) if params[:user_id]
            @quote = Spree::Core::Importer::Order.import(user, quote_params)
            @quote_request.update_columns(spree_order_id: @quote.id, status: Spree::QuoteRequest.statuses[:approved])
            redirect_to quote_request_admin_quote_url(@quote)
          end

          private
          def load_quote_request
            @quote_request = Spree::QuoteRequest.find(params[:id])
          end

          def quote_params
            {
              created_by_id: try_spree_current_user.try(:id),
              frontend_viewable: false,
              store_id: current_store.try(:id),
              is_quote: true,
              quote_state: 'created'
            }.with_indifferent_access
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes_controller.rb
module Spree
  if defined? Spree::Backend
    module Admin
      class QuotesController < Spree::Admin::BaseController
        before_action :load_quote, only: [:edit, :update, :unfinalize_adjustments, :finalize_adjustments, :cart, :send_to_user, :save_as_order, :destroy, :quote_request]
        around_action :lock_quote, only: [:update]

        rescue_from Spree::Quote::InsufficientStock, with: :insufficient_stock_error

        respond_to :html

        def index
          query_present = params[:q]
          params[:q] ||= {}
          params[:q][:s] ||= 'created_at desc'
          params[:q][:completed_at_not_null] = ''

          if params[:q][:created_at_gt].present?
            params[:q][:created_at_gt] = begin
                                           Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day
                                         rescue
                                           ""
                                         end
          end

          if params[:q][:created_at_lt].present?
            params[:q][:created_at_lt] = begin
                                           Time.zone.parse(params[:q][:created_at_lt]).end_of_day
                                         rescue
                                           ""
                                         end
          end

          @search = Spree::Quote.accessible_by(current_ability, :index).ransack(params[:q])

          # lazy loading other models here (via includes) may result in an invalid query
          # e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"
          # see https://github.com/spree/spree/pull/3919
          @quotes = if query_present
            @search.result(distinct: true)
          else
            @search.result
          end

          @quotes = @quotes.
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:orders_per_page])
        end

        def new
          user = Spree.user_class.find_by_id(params[:user_id]) if params[:user_id]
          @quote = Spree::Core::Importer::Order.import(user, quote_params)
          redirect_to cart_admin_quote_url(@quote)
        end

        def edit
          require_ship_address

          unless @quote.completed?
            @quote.refresh_shipment_rates
          end
        end

        def cart
          unless @quote.completed?
            @quote.refresh_shipment_rates
          end
          if @quote.shipped_shipments.count > 0
            redirect_to edit_admin_quote_url(@quote)
          end
        end

        def quote_request
          @comment = Spree::QuoteComment.new(by_admin: true, commentable: (@quote_request = @quote.quote_request))
        end

        def unfinalize_adjustments
          adjustments = @quote.all_adjustments.finalized
          adjustments.each(&:unfinalize!)
          flash[:success] = Spree.t(:all_adjustments_unfinalized)

          respond_with(@quote) { |format| format.html { redirect_to(spree.admin_quote_adjustments_path(@quote)) } }
        end

        def finalize_adjustments
          adjustments = @quote.all_adjustments.not_finalized
          adjustments.each(&:finalize!)
          flash[:success] = Spree.t(:all_adjustments_finalized)

          respond_with(@quote) { |format| format.html { redirect_to(spree.admin_quote_adjustments_path(@quote)) } }
        end

        def send_to_user
          @quote.send_quote_to_user
          flash[:success] = Spree.t(:quote_sent_to_user)

          redirect_to(spree.edit_admin_quote_path(@quote))
        end

        def save_as_order
          @quote.finish_quote

          flash[:success] = Spree.t(:saved_as_order)

          redirect_to(spree.edit_admin_order_path(@quote))
        end

        def destroy
          @quote.destroy

          flash[:success] = Spree.t(:discarded_quote)

          respond_with(@quote) do |format|
            format.html { redirect_to(spree.admin_quotes_path) }
            format.js { render partial: 'spree/admin/quotes/destroy' }
          end
        end

        private

        def quote_params
          {
            created_by_id: try_spree_current_user.try(:id),
            frontend_viewable: false,
            store_id: current_store.try(:id),
            is_quote: true,
            quote_state: 'created'
          }.with_indifferent_access
        end

        def load_quote
          @quote = Spree::Quote.includes(:adjustments).find_by_number!(params[:id])
          authorize! action, @quote
        end

        def model_class
          Spree::Quote
        end

        def insufficient_stock_error
          flash[:error] = Spree.t(:insufficient_stock_for_quote)
          redirect_to cart_admin_quote_url(@quote)
        end

        def require_ship_address
          if @quote.ship_address.nil?
            flash[:notice] = Spree.t(:fill_in_customer_info)
            redirect_to edit_admin_quote_customer_url(@quote)
          end
        end
      end
    end
  end
end

app/controllers/spree/quotes_controller.rb
module Spree
  if defined? Spree::Frontend
    class QuotesController < Spree::StoreController
      respond_to :html
      before_action :load_quote, only: [:show, :edit, :destroy, :update, :approve, :place_into_cart]
      before_action :check_request_owner

      def show
      end

      def destroy
        if @quote.update_attributes(is_quote: false)
          redirect_to account_path
        end
      end

      def approve
        @quote.approve!

        flash[:success] = Spree.t(:approval_requested)

        respond_with(@quote) do |format|
          format.html { redirect_to quote_request_path(@quote.quote_request) }
        end
      end

      def place_into_cart
        @quote.update!
        session[:current_quote_number] = @quote.number

        redirect_to spree.checkout_state_path(@quote.state)
      end

      # Detach quote from cart
      def leave_it
        session.delete(:current_quote_number) if session.has_key?(:current_quote_number)
        @order = @simple_current_order = @current_order = nil

        redirect_to spree.root_path
      end

      private
      def load_quote
        @quote = Spree::Quote.unscoped.find_by_number!(params[:id])
      end

      def check_authorization
        @user ||= spree_current_user
        authorize! params[:action].to_sym, @user
      end

      def check_request_owner
        if try_spree_current_user.blank? || try_spree_current_user.try(:admin?) || try_spree_current_user.try(:email) == @quote.email
          return
        else
          raise CanCan::AccessDenied
        end
      end
    end
  end
end

app/helpers/spree/admin/quotes_helper.rb
module Spree
  if defined? Backend
    module Admin
      module QuotesHelper
      end
    end
  end
end

app/views/spree/admin/quotes/adjustments/_adjustment.html.erb
<%
  @edit_url = edit_admin_quote_adjustment_path(@quote, adjustment)
  @delete_url = admin_quote_adjustment_path(@quote, adjustment)
%>
<tr id="<%= spree_dom_id(adjustment) %>"
    data-hook="adjustment_row"
    class="<%= cycle('odd', 'even')%> <%= "adjustment-ineligible" if !adjustment.eligible? %>"
    >
  <td class="align-center"><%= display_adjustable(adjustment.adjustable) %></td>
  <td class="align-center"><%= adjustment.label %></td>
  <td class="align-center"><%= adjustment.display_amount.to_html %></td>
  <td class="align-center"><%= adjustment_state(adjustment) %></td>
  <td class='actions'>
    <% unless adjustment.finalized? %>
      <% if can?(:update, adjustment) %>
        <%= link_to_edit adjustment, :no_text => true %>
      <% end %>

      <% if can?(:destroy, adjustment) %>
        <%= link_to_delete adjustment, :no_text => true %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/quotes/adjustments/_adjustments_table.html.erb
<table class="index adjustments" data-hook="adjustments">
  <thead data-hook="adjustmment_head">
    <tr>
      <th><%= Spree::Adjustment.human_attribute_name(:adjustable) %></th>
      <th><%= Spree::Adjustment.human_attribute_name(:label) %></th>
      <th><%= Spree::Adjustment.human_attribute_name(:amount) %></th>
      <th><%= Spree::Adjustment.human_attribute_name(:state) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "adjustment", :collection => @adjustments %>
    <tr data-hook="adjustment_buttons">
      <td class="align-center" colspan='4'>
        <% if can? :update, Spree::Adjustment %>
            <%= button_to Spree.t(:unfinalize_all_adjustments), adjustments_unfinalize_admin_quote_path(@quote), method: :get, class: "col-md-5" %><br/>
            <%= button_to Spree.t(:finalize_all_adjustments), adjustments_finalize_admin_quote_path(@quote), method: :get, class: "col-md-5" %>
        <% end %>
      </td>
      <td class='actions'>&nbsp;</td>
    </tr>
  </tbody>
</table>

app/views/spree/admin/quotes/adjustments/_form.html.erb
<div data-hook="admin_adjustment_form_fields">
  <div class="row">

    <div class="col-md-3">
      <%= f.field_container :amount do %>
        <%= f.label :amount, class: 'required' %>
        <%= text_field :adjustment, :amount, class: 'full-width', value: (number_to_currency(f.object.amount, :precision => 2, unit: '$ ') || 0) %>
        <%= f.error_message_on :amount %>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.field_container :label do %>
        <%= f.label :label, class: 'required' %>
        <%= text_field :adjustment, :label, class: 'full-width' %>
        <%= f.error_message_on :label %>
      <% end %>
    </div>

    <% if Spree::AdjustmentReason.active.any? %>
      <div class="col-md-3">
        <%= f.field_container :label do %>
          <%= f.label :adjustment_reason_id %><br/>
          <%= f.collection_select(:adjustment_reason_id, reasons_for(@adjustment), :id, :name, {include_blank: true}, {"data-placeholder" => Spree.t(:select_a_reason), class: 'select2 full-width'}) %>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/spree/admin/quotes/adjustments/edit.html.erb
<%= render :partial => 'spree/admin/shared/quote_tabs', :locals => { :current => 'Adjustments' } %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::Adjustment), spree.admin_quote_adjustments_path(@quote)) %>
<% admin_breadcrumb("#{Spree.t('actions.edit')} #{Spree::Adjustment.model_name.human}") %>

<% content_for :page_actions do %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @adjustment } %>
<%= form_for @adjustment, :url => admin_quote_adjustment_path(@quote, @adjustment), :method => :put do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:continue) %>
      <%= link_to Spree.t('actions.cancel'), admin_quote_adjustments_url(@quote), :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/quotes/adjustments/index.html.erb
<%= render 'spree/admin/shared/quote_page_actions' %>

<%= render :partial => 'spree/admin/shared/quote_tabs', :locals => { :current => 'Adjustments' } %>

<% admin_breadcrumb(plural_resource_name(Spree::Adjustment)) %>

<% content_for :page_actions do %>
  <% if can? :create, Spree::Adjustment %>
    <li>
      <%= button_link_to Spree.t(:new_adjustment), new_admin_quote_adjustment_url(@quote) %>
    </li>
  <% end %>
<% end %>

<%= render :partial => 'adjustments_table' %>

<% if @quote.can_add_coupon? %>
  <div data-hook="adjustments_new_coupon_code">
    <%= text_field_tag "coupon_code", "", :placeholder => Spree.t(:coupon_code) %>
    <%= button Spree.t(:add_coupon_code), nil, 'submit', :id => "add_coupon_code" %>
  </div>
<% end %>
<%= javascript_tag do -%>
  var order_number = '<%= @quote.number %>';
<% end -%>

app/views/spree/admin/quotes/adjustments/new.html.erb
<%= render :partial => 'spree/admin/shared/quote_tabs', :locals => { :current => 'Adjustments' } %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::Adjustment), spree.admin_quote_adjustments_path(@quote)) %>
<% admin_breadcrumb(Spree.t(:new_adjustment)) %>


<% content_for :page_actions do %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @adjustment } %>

<%= form_for @adjustment, :url => admin_quote_adjustments_path do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:continue) %>
      <%= button_link_to Spree.t('actions.cancel'), admin_quote_adjustments_url(@quote) %>
    </div>
  </fieldset>
<% end %>