config/routes.rb
Spree::Core::Engine.routes.draw do
  patch '/save_quote_cart', to: 'orders#save_as_quote_cart', as: :save_as_quote_cart

  namespace :admin do
    resources :quotes, except: [:show] do
      member do
        get :cart
        get "/adjustments/unfinalize", to: "quotes#unfinalize_adjustments"
        get "/adjustments/finalize", to: "quotes#finalize_adjustments"
        post :send_to_user
        post :save_as_order
        get :quote_request
      end

      resources :adjustments, controller: "quotes/adjustments"
      resource :customer, controller: "quotes/customer_details"

      collection do
        resources 'quote_requests', controller: 'quotes/requests', only: [:index, :show] do
          member do
            get 'create_quote', to: 'quotes/requests#create_quote'
          end
        end
      end
    end
  end

  resources :quotes do
    member do
      get :approve
      get :place_into_cart
      get :leave_it
    end
  end

  resources :quote_requests, only: [:new, :create, :show] do
    post :comment, to: 'quote_requests#create_comment', on: :collection
  end
end

app/models/spree/quote.rb
module Spree
  class Quote < Order
    # Callbacks
    after_initialize :set_initial_config

    # Associations
    has_one :quote_details, class_name: Spree::QuoteDetails, foreign_key: 'spree_order_id', dependent: :destroy
    has_one :quote_request, class_name: Spree::QuoteRequest, foreign_key: 'spree_order_id', dependent: :nullify

    delegate :processing_quote?, :approved_by_user?,
      :needs_revision?, :requested?, :confirmation_delivered?, to: :quote_details, prefix: true

    # Scopes
    default_scope { as_quote }
    scope :as_quote, ->() { where(is_quote: true) }

    # Overriding methods
    def self.model_name
      ActiveModel::Name.new(self, nil, "Quote")
    end

    def quote_details
      super || (self.id?? Spree::QuoteDetails.find_or_create_by(spree_order_id: self.id) : nil)
    end

    # Redefining checkout_flow by adding quote step
    # checkout_flow do
    #   go_to_state :quote, if: ->(quote) { quote.quote_state == "ready" || quote.is_quote? || quote.quote_closed? }
    #   go_to_state :address
    #   go_to_state :delivery
    #   go_to_state :payment, if: ->(order) { order.payment_required? }
    #   go_to_state :confirm
    # end
    #
    # state_machine.before_transition from: :quote, do: :ensure_line_items_present

    def send_quote_to_user
      updater.update_quote_state
      updater.update
      deliver_quote_email
    end

    def finish_quote
      update_column(:quote_closed, true)
      updater.update_quote_state
      updater.update
      deliver_quote_finished_email
    end

    def send_quote_request_notification
      deliver_quote_request_notification
    end

    def approve!
      touch :quote_approved_at
      quote_details.update_column(:approved, true)
      updater.update_quote_state
      updater.update
    end

    def deliver_quote_email
      Spree::QuoteMailer.quote_email(self).deliver_later
      quote_details.update_column(:confirmation_delivered, true)
    end

    def deliver_quote_finished_email
      Spree::QuoteMailer.finish_quote_email(self).deliver_later
      update_column(:quote_closed, true)
    end

    def deliver_quote_request_notification
      Spree::QuoteMailer.quote_request_notification_email(self.quote_request).deliver_later
      Spree::QuoteMailer.admin_quote_request_notification_email(self.quote_request).deliver_later
      quote_details.update_column(:request_notification_delivered, true)
    end

    private
    def set_initial_config
      self.quote_details = Spree::QuoteDetails.find_or_initialize_by(spree_order_id: self.id)
    end
  end
end

app/controllers/spree/admin/quotes/adjustments_controller.rb
module Spree
  module Admin
    module Quotes
      class AdjustmentsController < ResourceController
        belongs_to 'spree/quote', find_by: :number

        create.after :update_totals
        destroy.after :update_totals
        update.after :update_totals

        skip_before_action :load_resource, only: [:toggle_state, :edit, :update, :destroy]

        before_action :find_adjustment, only: [:destroy, :edit, :update]

        helper_method :reasons_for

        def index
          @adjustments = @quote.all_adjustments.order("created_at ASC")
        end

        private

        def find_adjustment
          # Need to assign to @object here to keep ResourceController happy
          @adjustment = @object = parent.all_adjustments.find(params[:id])
        end

        def update_totals
          @quote.reload.update!
        end

        # Override method used to create a new instance to correctly
        # associate adjustment with quote
        def build_resource
          parent.adjustments.build(order: parent)
        end

        def reasons_for(_adjustment)
          [
            Spree::AdjustmentReason.active.to_a,
            @adjustment.adjustment_reason
          ].flatten.compact.uniq.sort_by { |r| r.name.downcase }
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes/customer_details_controller.rb
module Spree
  if defined? Backend
    module Admin
      module Quotes
        class CustomerDetailsController < Spree::Admin::BaseController
          rescue_from Spree::Quote::InsufficientStock, with: :insufficient_stock_error

          before_action :load_quote

          def show
            edit
          end

          def edit
            country_id = Spree::Country.default.id
            @quote.build_bill_address(country_id: country_id) if @quote.bill_address.nil?
            @quote.build_ship_address(country_id: country_id) if @quote.ship_address.nil?

            @quote.bill_address.country_id = country_id if @quote.bill_address.country.nil?
            @quote.ship_address.country_id = country_id if @quote.ship_address.country.nil?
          end

          def update
            if @quote.contents.update_cart(quote_params)

              if should_associate_user?
                requested_user = Spree.user_class.find(params[:user_id])
                @quote.associate_user!(requested_user, @quote.email.blank?)
              end

              unless @quote.quote_request
                create_quote_request
                @quote.send_quote_request_notification
              end

              unless @quote.completed?
                @quote.next
                @quote.refresh_shipment_rates
              end

              flash[:success] = Spree.t('customer_details_updated')
              redirect_to cart_admin_quote_url(@quote)
            else
              render action: :edit
            end
          end

          private

          def quote_params
            params.require(:order).permit(
              :email,
              :use_billing,
              :company,
              :sales_rep_id,
              :doc_hours_from,
              :doc_hours_to,
              bill_address_attributes: permitted_address_attributes,
              ship_address_attributes: permitted_address_attributes,
            )
          end

          def load_quote
            @quote = Spree::Quote.includes(:adjustments).find_by_number!(params[:quote_id])
          end

          def model_class
            Spree::Quote
          end

          def should_associate_user?
            params[:guest_checkout] == "false" && params[:user_id] && params[:user_id].to_i != @quote.user_id
          end

          def insufficient_stock_error
            flash[:error] = Spree.t(:insufficient_stock_for_order)
            redirect_to edit_admin_quote_customer_url(@quote)
          end

          def create_quote_request
            @qr ||= @quote.create_quote_request(
              user_id: @quote.user_id,
              status: Spree::QuoteRequest.statuses[:approved]
            )
            @qr.guest_email = @quote.email if @qr.user_id.blank?
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes/requests_controller.rb
module Spree
  if defined? Backend
    module Admin
      module Quotes
        class RequestsController < Spree::Admin::BaseController
          before_action :load_quote_request, only: [:show, :create_quote]

          def index
            query_present = params[:q]

            @search = Spree::QuoteRequest.accessible_by(current_ability, :index).ransack(params[:q])
            @quote_requests = if query_present
              @search.result(distinct: true)
            else
              @search.result
            end

            @quote_requests = @quote_requests.page(params[:page]).
              per(params[:per_page] || Spree::Config[:orders_per_page])
          end

          def show
            @comment = Spree::QuoteComment.new(by_admin: true, commentable: @quote_request)
          end

          def create_quote
            user = Spree.user_class.find_by_id(params[:user_id]) if params[:user_id]
            @quote = Spree::Core::Importer::Order.import(user, quote_params)
            @quote_request.update_columns(spree_order_id: @quote.id, status: Spree::QuoteRequest.statuses[:approved])
            redirect_to quote_request_admin_quote_url(@quote)
          end

          private
          def load_quote_request
            @quote_request = Spree::QuoteRequest.find(params[:id])
          end

          def quote_params
            {
              created_by_id: try_spree_current_user.try(:id),
              frontend_viewable: false,
              store_id: current_store.try(:id),
              is_quote: true,
              quote_state: 'created'
            }.with_indifferent_access
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes_controller.rb
module Spree
  if defined? Spree::Backend
    module Admin
      class QuotesController < Spree::Admin::BaseController
        before_action :load_quote, only: [:edit, :update, :unfinalize_adjustments, :finalize_adjustments, :cart, :send_to_user, :save_as_order, :destroy, :quote_request]
        around_action :lock_quote, only: [:update]

        rescue_from Spree::Quote::InsufficientStock, with: :insufficient_stock_error

        respond_to :html

        def index
          query_present = params[:q]
          params[:q] ||= {}
          params[:q][:s] ||= 'created_at desc'
          params[:q][:completed_at_not_null] = ''

          if params[:q][:created_at_gt].present?
            params[:q][:created_at_gt] = begin
                                           Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day
                                         rescue
                                           ""
                                         end
          end

          if params[:q][:created_at_lt].present?
            params[:q][:created_at_lt] = begin
                                           Time.zone.parse(params[:q][:created_at_lt]).end_of_day
                                         rescue
                                           ""
                                         end
          end

          @search = Spree::Quote.accessible_by(current_ability, :index).ransack(params[:q])

          # lazy loading other models here (via includes) may result in an invalid query
          # e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"
          # see https://github.com/spree/spree/pull/3919
          @quotes = if query_present
            @search.result(distinct: true)
          else
            @search.result
          end

          @quotes = @quotes.
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:orders_per_page])
        end

        def new
          user = Spree.user_class.find_by_id(params[:user_id]) if params[:user_id]
          @quote = Spree::Core::Importer::Order.import(user, quote_params)
          redirect_to cart_admin_quote_url(@quote)
        end

        def edit
          require_ship_address

          unless @quote.completed?
            @quote.refresh_shipment_rates
          end
        end

        def cart
          unless @quote.completed?
            @quote.refresh_shipment_rates
          end
          if @quote.shipped_shipments.count > 0
            redirect_to edit_admin_quote_url(@quote)
          end
        end

        def quote_request
          @comment = Spree::QuoteComment.new(by_admin: true, commentable: (@quote_request = @quote.quote_request))
        end

        def unfinalize_adjustments
          adjustments = @quote.all_adjustments.finalized
          adjustments.each(&:unfinalize!)
          flash[:success] = Spree.t(:all_adjustments_unfinalized)

          respond_with(@quote) { |format| format.html { redirect_to(spree.admin_quote_adjustments_path(@quote)) } }
        end

        def finalize_adjustments
          adjustments = @quote.all_adjustments.not_finalized
          adjustments.each(&:finalize!)
          flash[:success] = Spree.t(:all_adjustments_finalized)

          respond_with(@quote) { |format| format.html { redirect_to(spree.admin_quote_adjustments_path(@quote)) } }
        end

        def send_to_user
          @quote.send_quote_to_user
          flash[:success] = Spree.t(:quote_sent_to_user)

          redirect_to(spree.edit_admin_quote_path(@quote))
        end

        def save_as_order
          @quote.finish_quote

          flash[:success] = Spree.t(:saved_as_order)

          redirect_to(spree.edit_admin_order_path(@quote))
        end

        def destroy
          @quote.destroy

          flash[:success] = Spree.t(:discarded_quote)

          respond_with(@quote) do |format|
            format.html { redirect_to(spree.admin_quotes_path) }
            format.js { render partial: 'spree/admin/quotes/destroy' }
          end
        end

        private

        def quote_params
          {
            created_by_id: try_spree_current_user.try(:id),
            frontend_viewable: false,
            store_id: current_store.try(:id),
            is_quote: true,
            quote_state: 'created'
          }.with_indifferent_access
        end

        def load_quote
          @quote = Spree::Quote.includes(:adjustments).find_by_number!(params[:id])
          authorize! action, @quote
        end

        def model_class
          Spree::Quote
        end

        def insufficient_stock_error
          flash[:error] = Spree.t(:insufficient_stock_for_quote)
          redirect_to cart_admin_quote_url(@quote)
        end

        def require_ship_address
          if @quote.ship_address.nil?
            flash[:notice] = Spree.t(:fill_in_customer_info)
            redirect_to edit_admin_quote_customer_url(@quote)
          end
        end
      end
    end
  end
end

app/controllers/spree/quotes_controller.rb
module Spree
  if defined? Spree::Frontend
    class QuotesController < Spree::StoreController
      respond_to :html
      before_action :load_quote, only: [:show, :edit, :destroy, :update, :approve, :place_into_cart]
      before_action :check_request_owner

      def show
      end

      def destroy
        if @quote.update_attributes(is_quote: false)
          redirect_to account_path
        end
      end

      def approve
        @quote.approve!

        flash[:success] = Spree.t(:approval_requested)

        respond_with(@quote) do |format|
          format.html { redirect_to quote_request_path(@quote.quote_request) }
        end
      end

      def place_into_cart
        @quote.update!
        session[:current_quote_number] = @quote.number

        redirect_to spree.checkout_state_path(@quote.state)
      end

      # Detach quote from cart
      def leave_it
        session.delete(:current_quote_number) if session.has_key?(:current_quote_number)
        @order = @simple_current_order = @current_order = nil

        redirect_to spree.root_path
      end

      private
      def load_quote
        @quote = Spree::Quote.unscoped.find_by_number!(params[:id])
      end

      def check_authorization
        @user ||= spree_current_user
        authorize! params[:action].to_sym, @user
      end

      def check_request_owner
        if try_spree_current_user.blank? || try_spree_current_user.try(:admin?) || try_spree_current_user.try(:email) == @quote.email
          return
        else
          raise CanCan::AccessDenied
        end
      end
    end
  end
end

app/helpers/spree/admin/quotes_helper.rb
module Spree
  if defined? Backend
    module Admin
      module QuotesHelper
      end
    end
  end
end

app/views/spree/admin/quotes/_add_line_item.html.erb
<div id="add-line-item" data-hook>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:add_product) %></legend>

    <div class="col-md-9">
      <div data-hook="add_product_name" class="field">
        <%= label_tag :add_line_item_variant_id, Spree.t(:name_or_sku) %>
        <%= text_field_tag :add_line_item_variant_id, "", :class => "variant_autocomplete full-width" %>
      </div>
    </div>

  </fieldset>

  <div id="stock_details"></div>
</div>

app/views/spree/admin/quotes/_add_product.html.erb
<div id="add-line-item" class="js-shipment-add-variant" data-hook>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:add_product) %></legend>

    <div class="col-md-9">
      <div data-hook="add_product_name" class="field">
        <%= label_tag :add_variant_id, Spree.t(:name_or_sku) %>
        <%= text_field_tag :add_variant_id, "", :class => "variant_autocomplete full-width" %>
      </div>
    </div>

  </fieldset>

  <div id="stock_details"></div>
</div>

app/views/spree/admin/quotes/_add_sales_rep_company.erb
<fieldset class="no-border-bottom" id="add-sales-rep-company" data-hook="add_sales_rep_company">
  <legend align="center"><%= Spree.t(:sales_rep) %></legend>

  <div class="col-md-12">
    <div data-hook="add_sales_rep">
      <%= f.field_container :sales_rep do %>
        <div class="pull-left"><%= f.label :sales_rep_id, Spree.t(:sales_rep_label) %></div>
        <div class="pull-left margin-left-5"><%= f.field_hint :sales_rep %></div>
        <%= f.collection_select(:sales_rep_id,
          Spree.user_class.sales_rep, :id, :email,
          { :class => 'select2',
            :selected => try_spree_current_user.id }) %>
        <%= f.error_message_on :sales_rep %>
      <% end %>
    </div>
  </div>

  <div class="col-md-12">
    <div data-hook="add_company">
      <%= f.field_container :company do %>
        <div class="pull-left"><%= f.label :company, Spree.t(:company) %></div>
        <div class="pull-left margin-left-5"><%= f.field_hint :company %></div>
        <%= f.text_field(:company, {placeholder: "Company Name", class: "full-width"}) %>
        <%= f.error_message_on :company %>
      <% end %>
    </div>
  </div>

  <%= render partial: 'spree/admin/shared/company_doc_hours', locals: { f: f } %>
</fieldset>

app/views/spree/admin/quotes/_adjustments.html.erb
<fieldset class="no-border-bottom">
  <legend><%= title %></legend>
  <table>
    <thead>
      <tr>
        <th><%= Spree::Adjustment.human_attribute_name(:name)%></th>
        <th><%= Spree::Adjustment.human_attribute_name(:amount)%></th>
      </tr>
    </thead>
    <tbody data-hook="order_details_adjustments"  class="with-border">
      <% adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><strong><%= label %>:</strong></td>
          <td class="total align-center"><span><%= Spree::Money.new(adjustments.sum(&:amount), currency: adjustments.first.order.try(:currency)) %></span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</fieldset>

app/views/spree/admin/quotes/_destroy.js.erb
<% success = flash.discard(:success)
if success %>
  show_flash('success', "<%= j success %>")
<% end %>
if(window.location.pathname != '<%= spree.admin_quotes_path %>'){
  window.location.href = '<%= spree.admin_quotes_path %>'
}

app/views/spree/admin/quotes/_form.html.erb
 <div data-hook="admin_quote_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
  <% end %>

  <% if !Spree::Order.checkout_step_names.include?(:delivery) %>
    <%= render :partial => "spree/admin/quotes/line_items", :locals => { :quote => quote } %>
  <% end %>

  <div class="js-order-line-item-adjustments <%= "hidden" if quote.line_item_adjustments.eligible.none? %>">
    <%= render :partial => "spree/admin/quotes/adjustments", :locals => {
          :adjustments => @quote.line_item_adjustments,
          :quote => quote,
          :title => Spree.t(:line_item_adjustments)
     } %>
  </div>

  <div class="js-order-shipment-adjustments <%= "hidden" if quote.shipment_adjustments.eligible.none? %>">
    <%= render :partial => "spree/admin/quotes/adjustments", :locals => {
          :adjustments => @quote.shipment_adjustments,
          :quote => quote,
          :title => Spree.t(:shipment_adjustments)
     } %>
  </div>

  <div class="js-order-adjustments <%= "hidden" if quote.adjustments.eligible.none? %>">
    <%= render :partial => "spree/admin/quotes/adjustments", :locals => {
          :adjustments => @quote.adjustments,
          :quote => quote,
          :title => Spree.t(:quote_adjustments)
     } %>
  </div>

  <% if quote.line_items.exists? %>
    <fieldset class="no-border-bottom" id="quote-total" data-hook="order_details_total">
      <legend><%= Spree.t(:quote_total) %></legend>
      <span class="order-total"><%= quote.display_total %></span>
    </fieldset>
  <% end %>

  <%= javascript_tag do -%>
    var order_number = '<%= @quote.number %>';
  <% end -%>
</div>

app/views/spree/admin/quotes/_line_items.html.erb
<table class="line-items index" data-hook="line-items">
  <colgroup>
    <col style="width: 10%;" />
    <col style="width: 45%;" />
    <col style="width: 10%;" />
    <col style="width: 10%;" />
    <col style="width: 10%;" />
    <col style="width: 15%;" />
  </colgroup>

  <thead>
    <tr>
      <th colspan="2"><%= Spree::Product.human_attribute_name(:name) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:price) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:quantity) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:total) %></th>
      <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <%# Rendered by JS %>
  </tbody>
</table>

app/views/spree/admin/quotes/_line_items_edit_form.html.erb
<div data-hook="admin_order_form_fields" class="js-order-cart-page" data-order-number="<%= quote.number %>">
  <% if @line_item.try(:errors).present? %>
      <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
  <% end %>

  <%= render :partial => "spree/admin/quotes/line_items", :locals => { :quote => quote } %>

  <% if can?(:update, @quote) && can?(:create, Spree::LineItem) %>
    <button class="js-add-line-item" disabled><%= t('spree.add_line_item') %></button>
  <% end %>

  <%= render "spree/admin/quotes/quote_details", { quote: @quote } %>
</div>

app/views/spree/admin/quotes/cart.html.erb
<%= render 'spree/admin/shared/quote_page_actions' %>

<%= render :partial => 'spree/admin/shared/quote_tabs', :locals => { :current => 'Cart' } %>

<% admin_breadcrumb(Spree.t(:cart)) %>


<div data-hook="admin_order_edit_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @quote } %>
</div>

<% if @quote.payments.exists? && @quote.is_risky? %>
    <%= render 'spree/admin/quotes/risk_analysis', latest_payment: @quote.payments.reorder("created_at DESC").first %>
<% end %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render :partial => 'line_items_edit_form', :locals => { :quote => @quote } %>
  </div>
</div>

app/views/spree/admin/quotes/index.html.erb
<% admin_breadcrumb(plural_resource_name(Spree::Quote)) %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_quote), new_admin_quote_url, :id => 'admin_new_quote' %>

    <%= button_link_to Spree.t(:quote_requests), admin_quote_requests_path, id: 'admin_quote_requests' %>
  </li>
<% end if can? :create, Spree::Quote %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_quotes_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="field-block col-md-4">
          <div class="date-range-filter field">
            <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
            <div class="date-range-fields">
              <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>

              <span class="range-divider">
                <i class="fa fa-arrow-right"></i>
              </span>

              <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="field">
            <%= label_tag :q_email_cont, Spree.t(:email) %>
            <%= f.text_field :email_cont %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="field">
            <%= label_tag :q_state_eq, Spree.t(:status) %>
            <!-- TODO state_eq should receive new states coming from quote -->
            <%= f.select :state_eq, Spree::Quote.state_machines[:state].states.collect {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2 full-width' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="field">
            <%= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%= f.text_field :bill_address_firstname_start, :size => 25 %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="field">
            <%= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%= f.text_field :bill_address_lastname_start, :size => 25%>
          </div>
        </div>

        <div class="col-md-4">
          <div class="field" data-hook="sku-select">
            <%= label_tag :q_line_items_variant_id_in, Spree.t(:variant) %>
            <%= f.text_field :line_items_variant_id_in, class: "variant_autocomplete full-width" %>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_quotes_index_search_buttons">
          <%= button Spree.t(:filter_results) %>
        </div>
      </div>
    <% end %>
<% end %>

<%= paginate @quotes, theme: "solidus_admin" %>

<% if @quotes.any? %>
  <table class="index" id="listing_quotes" data-hook>
    <colgroup>
       <col style="width: 13%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 12%;">
       <% if Spree::Quote.checkout_step_names.include?(:delivery) %>
         <col style="width: 12%;">
       <% end %>
       <col style="width: 25%;">
       <col style="width: 10%;">
       <col style="width: 8%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_quotes_index_headers">
        <th><%= sort_link @search, :created_at, 'Quote Date' %></th>
        <th><%= sort_link @search, :number %></th>
        <th><%= sort_link @search, :quote_state %></th>
        <th><%= sort_link @search, :email %></th>
        <th><%= sort_link @search, :quote_details_approved_by_user?, "Approved?" %></th>
        <th><%= sort_link @search, :total %></th>
        <th data-hook="admin_quotes_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @quotes.each do |quote| %>
      <tr data-hook="admin_quotes_index_rows" class="state-<%= quote.state.downcase %> <%= cycle('odd', 'even') %>">
        <td class="align-center"><%= l quote.created_at.to_date %></td>
        <td class="align-center"><%= link_to quote.number, edit_admin_quote_path(quote) %></td>
        <td class="align-center"><span><%= quote.quote_state %></span></td>
        <td>
          <% if quote.user %>
            <%= link_to quote.email, edit_admin_user_path(quote.user) %>
          <% else %>
            <%= mail_to quote.email %>
          <% end %>
        </td>
        <td class="align-center"><span><%= quote.quote_details_approved_by_user? %></span></td>
        <td class="align-center"><%= quote.display_total.to_html %></td>
        <td class='actions align-center' data-hook="admin_quotes_index_row_actions">
          <%= link_to_edit_url edit_admin_quote_path(quote), :title => "admin_edit_#{dom_id(quote)}", :no_text => true %>
          &nbsp;
          <%= link_to '', admin_quote_path(quote),
            class: 'delete-resource fa fa-trash icon_link with-tip no-text',
            data: { confirm: Spree.t(:are_you_sure), method: :delete } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="col-md-9 no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Quote,
                 new_resource_url: spree.new_admin_quote_path %>
  </div>
<% end %>

<%= paginate @quotes, theme: "solidus_admin" %>