config/routes.rb
Spree::Core::Engine.routes.draw do
  patch '/save_quote_cart', to: 'orders#save_as_quote_cart', as: :save_as_quote_cart

  namespace :admin do
    resources :quotes, except: [:show] do
      member do
        get :cart
        get "/adjustments/unfinalize", to: "quotes#unfinalize_adjustments"
        get "/adjustments/finalize", to: "quotes#finalize_adjustments"
        post :send_to_user
        post :save_as_order
        get :quote_request
      end

      resources :adjustments, controller: "quotes/adjustments"
      resource :customer, controller: "quotes/customer_details"

      collection do
        resources 'quote_requests', controller: 'quotes/requests', only: [:index, :show] do
          member do
            get 'create_quote', to: 'quotes/requests#create_quote'
          end
        end
      end
    end
  end

  resources :quotes do
    member do
      get :approve
      get :place_into_cart
      get :leave_it
    end
  end

  resources :quote_requests, only: [:new, :create, :show] do
    post :comment, to: 'quote_requests#create_comment', on: :collection
  end
end

app/views/spree/admin/shared/_quote_page_actions.html.erb
<% content_for :page_actions do %>
  <% if @quote.is_quote? && !@quote.quote_details_confirmation_delivered? %>
    <li><%= button_link_to Spree.t(:send_to_user), send_to_user_admin_quote_url(@quote), :method => :post %></li>
  <% end %>

  <% if @quote.is_quote? && @quote.quote_details_approved_by_user? %>
    <li><%= button_link_to Spree.t(:save_quote_as_order), save_as_order_admin_quote_url(@quote), :method => :post %></li>
  <% end %>

  <% if @quote.is_quote? && @quote.quote_details_confirmation_delivered? &&
    !@quote.quote_details_approved_by_user? %>
    <li><%= Spree.t(:waiting_user_approval) %></li>
  <% end %>
<% end %>

app/views/spree/admin/shared/_quote_submenu.html.erb
<nav>
  <ul class="tabs" data-hook="admin_quote_tabs">
    <% if @quote.quote_request.present? %>
      <li class="<%= "active" if current == "Request" %>" data-hook='admin_quote_tabs_quote_request'>
        <%= link_to Spree.t(:request), spree.quote_request_admin_quote_url(@quote) %>
      </li>
    <% end %>

    <% if (@quote.shipments.count == 0 || @quote.shipped_shipments.count == 0) %>
      <li class="<%= "active" if current == "Cart" %>" data-hook='admin_quote_tabs_quote_details'>
        <%= link_to Spree.t(:cart), spree.cart_admin_quote_url(@quote) %>
      </li>
    <% end %>

    <li class="<%= "active" if (current == "Customer Details") %>" data-hook='admin_order_tabs_customer_details'>
      <% if can?(:update, @quote) %>
        <%= link_to Spree.t(:customer), spree.edit_admin_quote_customer_url(@quote) %>
      <% else %>
        <%= link_to Spree.t(:customer), spree.admin_quote_customer_url(@quote) %>
      <% end %>
    </li>

    <% if can? :display, Spree::Adjustment %>
      <li class="<%= "active" if current == "Adjustments" %>" data-hook='admin_quote_tabs_adjustments'>
        <%= link_to plural_resource_name(Spree::Adjustment), spree.admin_quote_adjustments_url(@quote) %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/spree/admin/shared/_quote_summary.html.erb
<header id="quote_tab_summary" data-hook>
  <dl class="additional-info">
    <dt id="quote_status" data-hook><%= Spree.t(:status) %>:</dt>
    <dd><span><%= @quote.quote_state %></span></dd>

    <% if @quote.user.present? %>
      <dt data-hook='admin_quote_user_link'><%= Spree.t(:user) %>:</dt>
      <dd id='quote_user_link'><%= link_to @quote.user.email, spree.edit_admin_user_path(@quote.user) %></dd>
    <% end %>

    <%= render partial: 'spree/admin/shared/sales_and_company_tab_summary' %>

    <% if @quote.quote_details_approved_by_user? %>
      <dt><%= Spree::QuoteDetails.human_attribute_name(:approved_at) %></dt>
      <dd><%= pretty_time(@quote.quote_approved_at) %></dd>
    <% else %>
      <dt><%= Spree.t(:approval_status) %></dt>
      <dd><%= Spree.t(:waiting_user_approval) %></dd>
    <% end %>

    <dt data-hook='admin_quote_tab_subtotal_title'><%= Spree::Quote.human_attribute_name(:item_total) %>:</dt>
    <dd id='item_total'><%= @quote.display_item_total.to_html %></dd>
    <% if checkout_steps.include?("delivery") && @quote.ship_total > 0 %>
      <dt data-hook='admin_quote_tab_ship_total_title'><%= Spree::Quote.human_attribute_name(:shipment_total) %>:</dt>
      <dd id='ship_total'><%= @quote.display_ship_total.to_html %></dd>
    <% end %>

    <% if @quote.included_tax_total != 0 %>
      <dt data-hook='admin_quote_tab_included_tax_title'><%= Spree::Quote.human_attribute_name(:included_tax_total) %>:</dt>
      <dd id='included_tax_total'><%= @quote.display_included_tax_total.to_html %></dd>
    <% end %>

    <% if @quote.additional_tax_total != 0 %>
      <dt data-hook='admin_quote_tab_additional_tax_title'><%= Spree::Quote.human_attribute_name(:additional_tax_total) %>:</dt>
      <dd id='additional_tax_total'><%= @quote.display_additional_tax_total.to_html %></dd>
    <% end %>

    <dt data-hook='admin_quote_tab_total_title'><%= Spree::Quote.human_attribute_name(:total) %>:</dt>
    <dd id='quote_total'><%= @quote.display_total.to_html %></dd>

    <%= link_to Spree.t(:discard_quote), admin_quote_path(@quote),
      class: 'text-center delete-resource fa fa-trash icon_link with-tip button',
      data: { confirm: Spree.t(:are_you_sure), method: :delete } %>
  </dl>
</header>

app/views/spree/admin/shared/_quote_tabs.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Quote), spree.admin_quotes_path) %>
<% admin_breadcrumb(link_to "##{@quote.number}", spree.edit_admin_quote_path(@quote)) %>

<% content_for :sidebar_title do %>
  <%= Spree.t(:quote_information) %>
<% end %>

<% content_for :sidebar do %>
  <%= render "spree/admin/shared/quote_summary", checkout_steps: @quote.checkout_steps %>
<% end %>

<% content_for :tabs do %>
  <%= render "spree/admin/shared/quote_submenu", current: current, checkout_steps: @quote.checkout_steps %>
<% end %>

app/views/spree/admin/shared/_sales_and_company_tab_summary.html.erb
<% if (@quote || @order).company.present? %>
  <dt data-hook='admin_quote_company'><%= Spree.t(:company) %>:</dt>
  <dd id='quote_company'><%= (@quote || @order).company %></dd>
<% end %>

<% if (@quote || @order).sales_rep.present? %>
  <dt data-hook='admin_quote_sales_rep_link'><%= Spree.t(:sales_rep) %>:</dt>
  <dd id='quote_sales_rep_link'><%= (@quote || @order).sales_rep.email %></dd>
<% end %>