config/routes.rb
Spree::Core::Engine.routes.draw do
  patch '/save_quote_cart', to: 'orders#save_as_quote_cart', as: :save_as_quote_cart

  namespace :admin do
    resources :quotes, except: [:show] do
      member do
        get :cart
        get "/adjustments/unfinalize", to: "quotes#unfinalize_adjustments"
        get "/adjustments/finalize", to: "quotes#finalize_adjustments"
        post :send_to_user
        post :save_as_order
        get :quote_request
      end

      resources :adjustments, controller: "quotes/adjustments"
      resource :customer, controller: "quotes/customer_details"

      collection do
        resources 'quote_requests', controller: 'quotes/requests', only: [:index, :show] do
          member do
            get 'create_quote', to: 'quotes/requests#create_quote'
          end
        end
      end
    end
  end

  resources :quotes do
    member do
      get :approve
      get :place_into_cart
      get :leave_it
    end
  end

  resources :quote_requests, only: [:new, :create, :show] do
    post :comment, to: 'quote_requests#create_comment', on: :collection
  end
end

app/models/spree/quote.rb
module Spree
  class Quote < Order
    # Callbacks
    after_initialize :set_initial_config

    # Associations
    has_one :quote_details, class_name: Spree::QuoteDetails, foreign_key: 'spree_order_id', dependent: :destroy
    has_one :quote_request, class_name: Spree::QuoteRequest, foreign_key: 'spree_order_id', dependent: :nullify

    delegate :processing_quote?, :approved_by_user?,
      :needs_revision?, :requested?, :confirmation_delivered?, to: :quote_details, prefix: true

    # Scopes
    default_scope { as_quote }
    scope :as_quote, ->() { where(is_quote: true) }

    # Overriding methods
    def self.model_name
      ActiveModel::Name.new(self, nil, "Quote")
    end

    def quote_details
      super || (self.id?? Spree::QuoteDetails.find_or_create_by(spree_order_id: self.id) : nil)
    end

    # Redefining checkout_flow by adding quote step
    # checkout_flow do
    #   go_to_state :quote, if: ->(quote) { quote.quote_state == "ready" || quote.is_quote? || quote.quote_closed? }
    #   go_to_state :address
    #   go_to_state :delivery
    #   go_to_state :payment, if: ->(order) { order.payment_required? }
    #   go_to_state :confirm
    # end
    #
    # state_machine.before_transition from: :quote, do: :ensure_line_items_present

    def send_quote_to_user
      updater.update_quote_state
      updater.update
      deliver_quote_email
    end

    def finish_quote
      update_column(:quote_closed, true)
      updater.update_quote_state
      updater.update
      deliver_quote_finished_email
    end

    def send_quote_request_notification
      deliver_quote_request_notification
    end

    def approve!
      touch :quote_approved_at
      quote_details.update_column(:approved, true)
      updater.update_quote_state
      updater.update
    end

    def deliver_quote_email
      Spree::QuoteMailer.quote_email(self).deliver_later
      quote_details.update_column(:confirmation_delivered, true)
    end

    def deliver_quote_finished_email
      Spree::QuoteMailer.finish_quote_email(self).deliver_later
      update_column(:quote_closed, true)
    end

    def deliver_quote_request_notification
      Spree::QuoteMailer.quote_request_notification_email(self.quote_request).deliver_later
      Spree::QuoteMailer.admin_quote_request_notification_email(self.quote_request).deliver_later
      quote_details.update_column(:request_notification_delivered, true)
    end

    private
    def set_initial_config
      self.quote_details = Spree::QuoteDetails.find_or_initialize_by(spree_order_id: self.id)
    end
  end
end

app/controllers/spree/admin/quotes/adjustments_controller.rb
module Spree
  module Admin
    module Quotes
      class AdjustmentsController < ResourceController
        belongs_to 'spree/quote', find_by: :number

        create.after :update_totals
        destroy.after :update_totals
        update.after :update_totals

        skip_before_action :load_resource, only: [:toggle_state, :edit, :update, :destroy]

        before_action :find_adjustment, only: [:destroy, :edit, :update]

        helper_method :reasons_for

        def index
          @adjustments = @quote.all_adjustments.order("created_at ASC")
        end

        private

        def find_adjustment
          # Need to assign to @object here to keep ResourceController happy
          @adjustment = @object = parent.all_adjustments.find(params[:id])
        end

        def update_totals
          @quote.reload.update!
        end

        # Override method used to create a new instance to correctly
        # associate adjustment with quote
        def build_resource
          parent.adjustments.build(order: parent)
        end

        def reasons_for(_adjustment)
          [
            Spree::AdjustmentReason.active.to_a,
            @adjustment.adjustment_reason
          ].flatten.compact.uniq.sort_by { |r| r.name.downcase }
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes/customer_details_controller.rb
module Spree
  if defined? Backend
    module Admin
      module Quotes
        class CustomerDetailsController < Spree::Admin::BaseController
          rescue_from Spree::Quote::InsufficientStock, with: :insufficient_stock_error

          before_action :load_quote

          def show
            edit
          end

          def edit
            country_id = Spree::Country.default.id
            @quote.build_bill_address(country_id: country_id) if @quote.bill_address.nil?
            @quote.build_ship_address(country_id: country_id) if @quote.ship_address.nil?

            @quote.bill_address.country_id = country_id if @quote.bill_address.country.nil?
            @quote.ship_address.country_id = country_id if @quote.ship_address.country.nil?
          end

          def update
            if @quote.contents.update_cart(quote_params)

              if should_associate_user?
                requested_user = Spree.user_class.find(params[:user_id])
                @quote.associate_user!(requested_user, @quote.email.blank?)
              end

              unless @quote.quote_request
                create_quote_request
                @quote.send_quote_request_notification
              end

              unless @quote.completed?
                @quote.next
                @quote.refresh_shipment_rates
              end

              flash[:success] = Spree.t('customer_details_updated')
              redirect_to cart_admin_quote_url(@quote)
            else
              render action: :edit
            end
          end

          private

          def quote_params
            params.require(:order).permit(
              :email,
              :use_billing,
              :company,
              :sales_rep_id,
              :doc_hours_from,
              :doc_hours_to,
              bill_address_attributes: permitted_address_attributes,
              ship_address_attributes: permitted_address_attributes,
            )
          end

          def load_quote
            @quote = Spree::Quote.includes(:adjustments).find_by_number!(params[:quote_id])
          end

          def model_class
            Spree::Quote
          end

          def should_associate_user?
            params[:guest_checkout] == "false" && params[:user_id] && params[:user_id].to_i != @quote.user_id
          end

          def insufficient_stock_error
            flash[:error] = Spree.t(:insufficient_stock_for_order)
            redirect_to edit_admin_quote_customer_url(@quote)
          end

          def create_quote_request
            @qr ||= @quote.create_quote_request(
              user_id: @quote.user_id,
              status: Spree::QuoteRequest.statuses[:approved]
            )
            @qr.guest_email = @quote.email if @qr.user_id.blank?
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes/requests_controller.rb
module Spree
  if defined? Backend
    module Admin
      module Quotes
        class RequestsController < Spree::Admin::BaseController
          before_action :load_quote_request, only: [:show, :create_quote]

          def index
            query_present = params[:q]

            @search = Spree::QuoteRequest.accessible_by(current_ability, :index).ransack(params[:q])
            @quote_requests = if query_present
              @search.result(distinct: true)
            else
              @search.result
            end

            @quote_requests = @quote_requests.page(params[:page]).
              per(params[:per_page] || Spree::Config[:orders_per_page])
          end

          def show
            @comment = Spree::QuoteComment.new(by_admin: true, commentable: @quote_request)
          end

          def create_quote
            user = Spree.user_class.find_by_id(params[:user_id]) if params[:user_id]
            @quote = Spree::Core::Importer::Order.import(user, quote_params)
            @quote_request.update_columns(spree_order_id: @quote.id, status: Spree::QuoteRequest.statuses[:approved])
            redirect_to quote_request_admin_quote_url(@quote)
          end

          private
          def load_quote_request
            @quote_request = Spree::QuoteRequest.find(params[:id])
          end

          def quote_params
            {
              created_by_id: try_spree_current_user.try(:id),
              frontend_viewable: false,
              store_id: current_store.try(:id),
              is_quote: true,
              quote_state: 'created'
            }.with_indifferent_access
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/quotes_controller.rb
module Spree
  if defined? Spree::Backend
    module Admin
      class QuotesController < Spree::Admin::BaseController
        before_action :load_quote, only: [:edit, :update, :unfinalize_adjustments, :finalize_adjustments, :cart, :send_to_user, :save_as_order, :destroy, :quote_request]
        around_action :lock_quote, only: [:update]

        rescue_from Spree::Quote::InsufficientStock, with: :insufficient_stock_error

        respond_to :html

        def index
          query_present = params[:q]
          params[:q] ||= {}
          params[:q][:s] ||= 'created_at desc'
          params[:q][:completed_at_not_null] = ''

          if params[:q][:created_at_gt].present?
            params[:q][:created_at_gt] = begin
                                           Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day
                                         rescue
                                           ""
                                         end
          end

          if params[:q][:created_at_lt].present?
            params[:q][:created_at_lt] = begin
                                           Time.zone.parse(params[:q][:created_at_lt]).end_of_day
                                         rescue
                                           ""
                                         end
          end

          @search = Spree::Quote.accessible_by(current_ability, :index).ransack(params[:q])

          # lazy loading other models here (via includes) may result in an invalid query
          # e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"
          # see https://github.com/spree/spree/pull/3919
          @quotes = if query_present
            @search.result(distinct: true)
          else
            @search.result
          end

          @quotes = @quotes.
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:orders_per_page])
        end

        def new
          user = Spree.user_class.find_by_id(params[:user_id]) if params[:user_id]
          @quote = Spree::Core::Importer::Order.import(user, quote_params)
          redirect_to cart_admin_quote_url(@quote)
        end

        def edit
          require_ship_address

          unless @quote.completed?
            @quote.refresh_shipment_rates
          end
        end

        def cart
          unless @quote.completed?
            @quote.refresh_shipment_rates
          end
          if @quote.shipped_shipments.count > 0
            redirect_to edit_admin_quote_url(@quote)
          end
        end

        def quote_request
          @comment = Spree::QuoteComment.new(by_admin: true, commentable: (@quote_request = @quote.quote_request))
        end

        def unfinalize_adjustments
          adjustments = @quote.all_adjustments.finalized
          adjustments.each(&:unfinalize!)
          flash[:success] = Spree.t(:all_adjustments_unfinalized)

          respond_with(@quote) { |format| format.html { redirect_to(spree.admin_quote_adjustments_path(@quote)) } }
        end

        def finalize_adjustments
          adjustments = @quote.all_adjustments.not_finalized
          adjustments.each(&:finalize!)
          flash[:success] = Spree.t(:all_adjustments_finalized)

          respond_with(@quote) { |format| format.html { redirect_to(spree.admin_quote_adjustments_path(@quote)) } }
        end

        def send_to_user
          @quote.send_quote_to_user
          flash[:success] = Spree.t(:quote_sent_to_user)

          redirect_to(spree.edit_admin_quote_path(@quote))
        end

        def save_as_order
          @quote.finish_quote

          flash[:success] = Spree.t(:saved_as_order)

          redirect_to(spree.edit_admin_order_path(@quote))
        end

        def destroy
          @quote.destroy

          flash[:success] = Spree.t(:discarded_quote)

          respond_with(@quote) do |format|
            format.html { redirect_to(spree.admin_quotes_path) }
            format.js { render partial: 'spree/admin/quotes/destroy' }
          end
        end

        private

        def quote_params
          {
            created_by_id: try_spree_current_user.try(:id),
            frontend_viewable: false,
            store_id: current_store.try(:id),
            is_quote: true,
            quote_state: 'created'
          }.with_indifferent_access
        end

        def load_quote
          @quote = Spree::Quote.includes(:adjustments).find_by_number!(params[:id])
          authorize! action, @quote
        end

        def model_class
          Spree::Quote
        end

        def insufficient_stock_error
          flash[:error] = Spree.t(:insufficient_stock_for_quote)
          redirect_to cart_admin_quote_url(@quote)
        end

        def require_ship_address
          if @quote.ship_address.nil?
            flash[:notice] = Spree.t(:fill_in_customer_info)
            redirect_to edit_admin_quote_customer_url(@quote)
          end
        end
      end
    end
  end
end

app/controllers/spree/quotes_controller.rb
module Spree
  if defined? Spree::Frontend
    class QuotesController < Spree::StoreController
      respond_to :html
      before_action :load_quote, only: [:show, :edit, :destroy, :update, :approve, :place_into_cart]
      before_action :check_request_owner

      def show
      end

      def destroy
        if @quote.update_attributes(is_quote: false)
          redirect_to account_path
        end
      end

      def approve
        @quote.approve!

        flash[:success] = Spree.t(:approval_requested)

        respond_with(@quote) do |format|
          format.html { redirect_to quote_request_path(@quote.quote_request) }
        end
      end

      def place_into_cart
        @quote.update!
        session[:current_quote_number] = @quote.number

        redirect_to spree.checkout_state_path(@quote.state)
      end

      # Detach quote from cart
      def leave_it
        session.delete(:current_quote_number) if session.has_key?(:current_quote_number)
        @order = @simple_current_order = @current_order = nil

        redirect_to spree.root_path
      end

      private
      def load_quote
        @quote = Spree::Quote.unscoped.find_by_number!(params[:id])
      end

      def check_authorization
        @user ||= spree_current_user
        authorize! params[:action].to_sym, @user
      end

      def check_request_owner
        if try_spree_current_user.blank? || try_spree_current_user.try(:admin?) || try_spree_current_user.try(:email) == @quote.email
          return
        else
          raise CanCan::AccessDenied
        end
      end
    end
  end
end

app/helpers/spree/admin/quotes_helper.rb
module Spree
  if defined? Backend
    module Admin
      module QuotesHelper
      end
    end
  end
end

app/views/spree/admin/quotes/customer_details/_form.html.erb
<fieldset data-hook="admin_customer_detail_form_fields" class="no-border-top">

  <% if can?(:update, @quote) %>
    <%= render :partial => 'spree/admin/quotes/add_sales_rep_company', locals: {f: f} %>
  <% end %>

  <fieldset class="index no-border-bottom" data-hook="customer_guest">
    <legend align="center"><%= Spree.t(:account) %></legend>

    <div data-hook="customer_fields" class="row">
      <div class="col-md-9">
        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email, :class => 'full-width' %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="field">
          <%= label_tag nil, Spree.t(:guest_checkout) %>
          <ul>
            <% if @quote.completed? %>
              <li>
                <%= @quote.user.nil? ? Spree.t(:say_yes) : Spree.t(:say_no) %>
              </li>
            <% else %>
              <% guest = @quote.user.nil? %>
              <li>
                <%= radio_button_tag :guest_checkout, true, guest %>
                <%= label_tag :guest_checkout_true, Spree.t(:say_yes) %>
              </li>
              <li>
                <%= radio_button_tag :guest_checkout, false, !guest, :disabled => @quote.cart? %>
                <%= label_tag :guest_checkout_false, Spree.t(:say_no) %>
              </li>
              <%= hidden_field_tag :user_id, @quote.user_id %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="row">
    <div class="col-md-6" data-hook="ship_address_wrapper">
      <fieldset class="no-border-bottom">
        <legend align="center"><%= Spree.t(:shipping_address) %></legend>
        <% if Spree::Config[:order_bill_address_used] %>
          <div class="field col-md-12">
            <span data-hook="use_billing">
              <%= check_box_tag 'order[use_billing]', '1', (@quote.ship_address.new_record? && @quote.bill_address == @quote.ship_address), class: "pull-left" %>
              <%= label_tag 'order[use_billing]', Spree.t(:use_billing_address), class: "col-md-6 margin-left-5" %>
            </span>
          </div>
        <% end %>

        <div class="js-shipping-address">
          <%= f.fields_for :ship_address do |sa_form| %>
            <%= render partial: 'spree/admin/shared/address_form', locals: { f: sa_form, type: "shipping" } %>
          <% end %>
        </div>
      </fieldset>
    </div>

    <% if Spree::Config[:order_bill_address_used] %>
      <div class="col-md-6" data-hook="bill_address_wrapper">
        <fieldset class="no-border-bottom">
          <legend align="center"><%= Spree.t(:billing_address) %></legend>
          <div class="js-billing-address" style="margin-top: 39px;">
            <%= f.fields_for :bill_address do |ba_form| %>
              <%= render :partial => 'spree/admin/shared/address_form', :locals => { :f => ba_form, :type => "billing" } %>
            <% end %>
          </div>
        </fieldset>
      </div>
    <% end %>
  </div>

  <div class="clear"></div>

  <div class="form-buttons filter-actions actions" data-hook="buttons">
    <%= button Spree.t('actions.update') %>
  </div>
</fieldset>

app/views/spree/admin/quotes/customer_details/edit.html.erb
<%= render :partial => 'spree/admin/shared/quote_tabs', :locals => { :current => 'Customer Details' } %>

<% admin_breadcrumb(Spree.t(:customer_details)) %>

<% content_for :page_actions do %>
<% end %>

<div class="js-customer-details" data-order-number="<%= @quote.number %>">
  <div id="select-customer" data-hook>
    <fieldset class="no-border-bottom">
      <legend align="center"><%= Spree.t(:customer_search) %></legend>
      <%= hidden_field_tag :customer_search,  nil, :class => 'fullwidth title' %>
    </fieldset>
  </div>

  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @quote } %>

  <%= form_for @quote, :as => :order, :url => admin_quote_customer_url(@quote) do |f| %>
    <%= render 'form', :f => f %>
  <% end %>
</div>

app/views/spree/admin/quotes/customer_details/show.html.erb
<%= render 'spree/admin/shared/quote_page_actions' %>

<%= render :partial => 'spree/admin/shared/quote_tabs', :locals => { :current => 'Customer Details' } %>

<% admin_breadcrumb(Spree.t(:customer_details)) %>


<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_quotes_list), admin_quotes_path %></li>
<% end %>


<main class="col-md-5">
  <section>
    <%= content_tag :h4, Spree.t(:account) %>
    <%= Spree.t(:email) %>: <%= @quote.email %><br>
    <%= Spree.t(:guest_checkout) %>: <%= @quote.user ? Spree.t(:yes) : Spree.t(:no) %>
  </section>

  <section>
    <%= content_tag :h4, Spree.t(:billing_address) %>
    <%= render "spree/admin/shared/address", address: @quote.bill_address %>
  </section>

  <section>
    <%= content_tag :h4, Spree.t(:shipping_address) %>
    <%= render "spree/admin/shared/address", address: @quote.ship_address %>
  </section>
</main>